language: python
python:
  - '3.8.1'

# safelist
branches:
  only:
    - staging
before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=condorvote_project.settings.travis

script:
  - python ./manage.py test --exclude-tag=fast