# Generated by Django 3.0.8 on 2020-07-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('classroom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('school', models.CharField(max_length=50)),
                ('school_class', models.CharField(max_length=20)),
                ('opening_vote', models.DateTimeField()),
                ('closing_vote', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('winners', models.CharField(max_length=100)),
                ('number_voters', models.IntegerField()),
                ('tickets_amount', models.IntegerField()),
                ('candidates', models.ManyToManyField(to='desk.Candidate')),
            ],
            options={
                'verbose_name': 'desk',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('ticket_number', models.IntegerField()),
                ('ticket_code', models.CharField(max_length=20)),
                (
                    'desk_tickets',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='desk.Desk'
                    )
                ),
            ],
            options={
                'verbose_name': 'ticket',
            },
        ),
    ]
